id: I53117650
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T05:43:08+00:00'
last_modified: '2022-06-08T16:06:24.636832+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2DB16429
  title: གསུང་ཐོར་བུ། བློ་གྲོས་རིན་ཆེན་སེངྒེ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    16FF:
      image_group_id: I1PD34084
      title: ''
      total_pages: 584
      order: 1
      base_file: 16FF.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
