id: P010593
initial_creation_type: ocr
source_metadata:
  id: bdr:W2DB16429
  title: གསུང་ཐོར་བུ། བློ་གྲོས་རིན་ཆེན་སེངྒེ
  author: ''
  volumes:
    c5ac575f0a294c6bb1d3017d6227432f:
      image_group_id: I1PD34084
      title: ''
      volume_number: 1
      total_pages: 584
      base_file: v001.txt
